version: "3"
services:
  book-portal-be:
    image: ugurcanerdogan/book-portal-be
    container_name: "book-portal-be"

  book-portal-fe:
    image: ugurcanerdogan/book-portal-fe
    container_name: "book-portal-fe"
    depends_on:
      - book-portal-be
  proxy:
    image: ugurcanerdogan/book-portal-proxy
    container_name: "book-portal-proxy"
    restart: always
    ports:
      - "80:80"